### ISSUE TITLE
Power BI explanation

### ISSUE THREAD

**Issue by robbiemorrison** [nimblelearn/datapackage-connector#1]
Could you perhaps write one sentence at the outset of your readme as to what [Power BI](https://en.wikipedia.org/wiki/Power_BI) is? As you can see, I had to resort to wikipedia. Even just that link would be a useful addition.

**Comment by michaelamadi** [comment]
Hi @robbiemorrison, thanks for taking the time to leave this feedback. The readme has been updated to include a direct link to the official [What is Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-overview) article.
